-- MySQL Script generated by MySQL Workbench
-- Sun Apr 21 16:12:10 2024
-- Model: DbBiblioteca    Version: 1.0

-- Del proyecto de Jorge Stiven, se realizan las mejoras requeridas.

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacion` (
  `titulo` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(100) NULL DEFAULT NULL,
  `autor` VARCHAR(100) NULL DEFAULT NULL,
  `num_paginas` INT NULL DEFAULT NULL,
  `cant_ejemplares` INT NULL DEFAULT NULL,
  `cant_prestados` INT NULL DEFAULT NULL,
  `cant_disponible` INT GENERATED ALWAYS AS ((`cant_ejemplares` - `cant_prestados`)) VIRTUAL,
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`area_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area_genero` (
  `titulo` VARCHAR(100) NOT NULL,
  `area_genero` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`titulo`, `area_genero`),
  CONSTRAINT `fk_Area_genero_1`
    FOREIGN KEY (`titulo`)
    REFERENCES `mydb`.`publicacion` (`titulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`edad_sugerida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`edad_sugerida` (
  `titulo` VARCHAR(100) NOT NULL,
  `edad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`titulo`, `edad`),
  CONSTRAINT `fk_edad_sug`
    FOREIGN KEY (`titulo`)
    REFERENCES `mydb`.`publicacion` (`titulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `idEmpleado` VARCHAR(100) NOT NULL,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Contrasena` VARCHAR(100) NULL DEFAULT NULL,
  `Correo` VARCHAR(255) NULL DEFAULT NULL,
  `Rol` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `Correo` VARCHAR(255) NOT NULL,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Contrasena` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prestamo` (
  `idPrestamo` VARCHAR(100) NOT NULL,
  `Fecha_prestamo` DATE NULL,
  `Fecha_devolucion` DATE NULL,
  `Estado` VARCHAR(100) NULL,
  `correo_usuario` VARCHAR(255) NULL,
  `titulo` VARCHAR(100) NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_correo_usuario_idx` (`correo_usuario` ASC) VISIBLE,
  INDEX `fk_titulo_publicacion_idx` (`titulo` ASC) VISIBLE,
  CONSTRAINT `fk_correo_usuario`
    FOREIGN KEY (`correo_usuario`)
    REFERENCES `mydb`.`usuario` (`Correo`),
  CONSTRAINT `fk_titulo_publicacion`
    FOREIGN KEY (`titulo`)
    REFERENCES `mydb`.`publicacion` (`titulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`grabacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grabacion` (
  `titulo` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(100) NULL DEFAULT NULL,
  `autor` VARCHAR(100) NULL DEFAULT NULL,
  `duracion` VARCHAR(100) NULL DEFAULT NULL,
  `cant_ejemplares` INT NULL DEFAULT NULL,
  `cant_prestados` INT NULL DEFAULT NULL,
  `cant_disponible` INT GENERATED ALWAYS AS ((`cant_ejemplares` - `cant_prestados`)) VIRTUAL,
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `titulo` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`titulo`, `genero`),
  CONSTRAINT `fk_genero`
    FOREIGN KEY (`titulo`)
    REFERENCES `mydb`.`grabacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`prestamo_g`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prestamo_g` (
  `idPrestamo` VARCHAR(100) NOT NULL,
  `Fecha_prestamo` DATE NULL DEFAULT NULL,
  `Fecha_devolucion` DATE NULL DEFAULT NULL,
  `Estado` VARCHAR(100) NULL DEFAULT NULL,
  `correo_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_correo_usuario_idx` (`correo_usuario` ASC) VISIBLE,
  INDEX `fk_titulo_grabacion_idx` (`titulo` ASC) VISIBLE,
  CONSTRAINT `fk_correo_usuario0`
    FOREIGN KEY (`correo_usuario`)
    REFERENCES `mydb`.`usuario` (`Correo`),
  CONSTRAINT `fk_titulo_grabacion`
    FOREIGN KEY (`titulo`)
    REFERENCES `mydb`.`grabacion` (`titulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `correo` VARCHAR(255) NOT NULL,
  `rolCreador` VARCHAR(100) NOT NULL,
  INDEX `fk_edad_sug0_idx` (`correo` ASC) VISIBLE,
  CONSTRAINT `fk_edad_sug0`
    FOREIGN KEY (`correo`)
    REFERENCES `mydb`.`usuario` (`Correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`registros_creados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registros_creados` (
  `idRegistro` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRegistro`))
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE TRIGGER TriggerUsuario BEFORE INSERT ON `user` FOR EACH ROW
BEGIN
INSERT INTO `registros_creados` (correo) VALUE (NEW.correo);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
