-- MySQL Script generated by MySQL Workbench
-- Sat Apr 13 20:15:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotecaPingui
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotecaPingui
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecaPingui` DEFAULT CHARACTER SET utf8 ;
USE `bibliotecaPingui` ;

-- -----------------------------------------------------
-- Table `bibliotecaPingui`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaPingui`.`Empleado` (
  `idEmpleado` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `contrasenha` VARCHAR(100) NULL,
  `correo` VARCHAR(255) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaPingui`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaPingui`.`Usuario` (
  `correo` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `contrasenha` VARCHAR(100) NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaPingui`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaPingui`.`Publicacion` (
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  `numPaginas` INT NULL,
  `cantEjemplares` INT NULL,
  `cantPrestados` INT NULL,
  `cantDisponibles` INT NULL DEFAULT (cantEjemplares - cantPrestados),
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaPingui`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaPingui`.`Prestamo` (
  `idPrestamo` VARCHAR(100) NOT NULL,
  `fechaPrestamo` DATE NULL,
  `fechaDevolucion` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `correoUsuario` VARCHAR(255) NULL,
  `tituloPublicacion` VARCHAR(100) NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fkCorreo_idx` (`correoUsuario` ASC) VISIBLE,
  INDEX `fkTitulo_idx` (`tituloPublicacion` ASC) VISIBLE,
  CONSTRAINT `fkCorreo`
    FOREIGN KEY (`correoUsuario`)
    REFERENCES `bibliotecaPingui`.`Usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkTitulo`
    FOREIGN KEY (`tituloPublicacion`)
    REFERENCES `bibliotecaPingui`.`Publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaPingui`.`edadSugerida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaPingui`.`edadSugerida` (
  `tituloPublicacion` VARCHAR(100) NOT NULL,
  `edadSugerida` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tituloPublicacion`, `edadSugerida`),
  CONSTRAINT `fkEdadSugerida`
    FOREIGN KEY (`tituloPublicacion`)
    REFERENCES `bibliotecaPingui`.`Publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaPingui`.`areaGenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaPingui`.`areaGenero` (
  `tituloPublicacion` VARCHAR(100) NOT NULL,
  `areaGenero` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tituloPublicacion`, `areaGenero`),
  CONSTRAINT `fkAreaGenero`
    FOREIGN KEY (`tituloPublicacion`)
    REFERENCES `bibliotecaPingui`.`Publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
